/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Contract, PvfPrices, PvfKey } from './types';

export const PVF_LABELS: Record<PvfKey, string> = {
  analogico: 'Analógico',
  semFio: 'Sem Fio',
  extensao: 'Extensão',
  dBasico: 'D.Básico',
  dEspecial: 'D.Especial',
  ipBasico: 'IP Básico',
  fCabeca: 'F.Cabeça',
  sMesa: 'S.Mesa',
  software: 'Software',
  virtual: 'Virtual',
};

export const INITIAL_PRICES: PvfPrices = {
  analogico: 15.0,
  semFio: 25.0,
  extensao: 10.0,
  dBasico: 20.0,
  dEspecial: 35.0,
  ipBasico: 30.0,
  fCabeca: 50.0,
  sMesa: 45.0,
  software: 12.0,
  virtual: 18.0,
};

export const INITIAL_CONTRACTS: Contract[] = [
  {
    id: 'C-01',
    contrato: 'Contrato 001/2025',
    secretaria: 'SEDUC - Secretaria de Educação',
    quantities: {
      analogico: 120,
      semFio: 80,
      extensao: 250,
      dBasico: 40,
      dEspecial: 15,
      ipBasico: 110,
      fCabeca: 10,
      sMesa: 8,
      software: 150,
      virtual: 50,
    },
    status: 'Ativo',
    dataAssinatura: '15/01/2025',
    observacoes: 'Contrato principal de telefonia das escolas da rede estadual.',
  },
  {
    id: 'C-02',
    contrato: 'Contrato 014/2025',
    secretaria: 'SESAU - Secretaria de Saúde',
    quantities: {
      analogico: 90,
      semFio: 120,
      extensao: 180,
      dBasico: 60,
      dEspecial: 25,
      ipBasico: 140,
      fCabeca: 15,
      sMesa: 12,
      software: 200,
      virtual: 80,
    },
    status: 'Ativo',
    dataAssinatura: '03/02/2025',
    observacoes: 'Atendimento de voz para os hospitais regionais e postos reguladores.',
  },
  {
    id: 'C-03',
    contrato: 'Contrato 044/2025',
    secretaria: 'SSP - Secretaria de Segurança Pública',
    quantities: {
      analogico: 45,
      semFio: 310,
      extensao: 90,
      dBasico: 30,
      dEspecial: 55,
      ipBasico: 210,
      fCabeca: 8,
      sMesa: 4,
      software: 350,
      virtual: 120,
    },
    status: 'Ativo',
    dataAssinatura: '23/02/2025',
    observacoes: 'Voz criptografada e radiocomunicação e terminais móveis integrados.',
  },
  {
    id: 'C-04',
    contrato: 'Contrato 002/2025',
    secretaria: 'SEFAZ - Secretaria da Fazenda',
    quantities: {
      analogico: 10,
      semFio: 30,
      extensao: 60,
      dBasico: 15,
      dEspecial: 20,
      ipBasico: 90,
      fCabeca: 4,
      sMesa: 2,
      software: 120,
      virtual: 40,
    },
    status: 'Ativo',
    dataAssinatura: '18/01/2025',
    observacoes: 'Atendimento dos postos fiscais de divisa interestadual.',
  },
  {
    id: 'C-05',
    contrato: 'Contrato 007/2025',
    secretaria: 'SEPLAN - Secretaria de Planejamento',
    quantities: {
      analogico: 15,
      semFio: 10,
      extensao: 30,
      dBasico: 8,
      dEspecial: 5,
      ipBasico: 35,
      fCabeca: 2,
      sMesa: 1,
      software: 40,
      virtual: 15,
    },
    status: 'Ativo',
    dataAssinatura: '10/01/2025',
    observacoes: 'Atendimento do prédio sede integrado de gestão governamental.',
  },
  {
    id: 'C-06',
    contrato: 'Contrato 089/2025',
    secretaria: 'SECULT - Secretaria de Cultura',
    quantities: {
      analogico: 25,
      semFio: 15,
      extensao: 40,
      dBasico: 5,
      dEspecial: 2,
      ipBasico: 15,
      fCabeca: 1,
      sMesa: 0,
      software: 25,
      virtual: 10,
    },
    status: 'Ativo',
    dataAssinatura: '12/03/2025',
    observacoes: 'Sistemas dos teatros, museus e bibliotecas públicas estaduais.',
  },
  {
    id: 'C-07',
    contrato: 'Contrato 112/2025',
    secretaria: 'SEAD - Sec de Administração',
    quantities: {
      analogico: 60,
      semFio: 50,
      extensao: 120,
      dBasico: 20,
      dEspecial: 10,
      ipBasico: 75,
      fCabeca: 5,
      sMesa: 3,
      software: 110,
      virtual: 30,
    },
    status: 'Ativo',
    dataAssinatura: '01/04/2025',
    observacoes: 'Gestão da telefonia da central de atendimento rápido ao cidadão.',
  },
  {
    id: 'C-08',
    contrato: 'Contrato 005/2025',
    secretaria: 'C.CIVIL - Casa Civil',
    quantities: {
      analogico: 12,
      semFio: 35,
      extensao: 45,
      dBasico: 10,
      dEspecial: 15,
      ipBasico: 40,
      fCabeca: 3,
      sMesa: 5,
      software: 50,
      virtual: 25,
    },
    status: 'Ativo',
    dataAssinatura: '08/01/2025',
    observacoes: 'Sistemas de alta prioridade de comunicação com o Palácio do Governo.',
  },
  {
    id: 'C-09',
    contrato: 'Contrato 201/2025',
    secretaria: 'PGE - Procuradoria Geral',
    quantities: {
      analogico: 5,
      semFio: 12,
      extensao: 55,
      dBasico: 18,
      dEspecial: 8,
      ipBasico: 50,
      fCabeca: 2,
      sMesa: 1,
      software: 65,
      virtual: 20,
    },
    status: 'Ativo',
    dataAssinatura: '02/05/2025',
    observacoes: 'Telefonia corporativa para o corpo jurídico e de procuradores do estado.',
  },
  {
    id: 'C-10',
    contrato: 'Contrato 076/2025',
    secretaria: 'SEMA - Secretaria de Meio Ambiente',
    quantities: {
      analogico: 35,
      semFio: 45,
      extensao: 70,
      dBasico: 12,
      dEspecial: 4,
      ipBasico: 45,
      fCabeca: 2,
      sMesa: 1,
      software: 60,
      virtual: 20,
    },
    status: 'Suspenso',
    dataAssinatura: '11/03/2025',
    observacoes: 'Contrato sob auditoria para expansão de postos de fiscalização florestal.',
  },
  {
    id: 'C-11',
    contrato: 'Contrato 143/2025',
    secretaria: 'SEEL - Secretaria de Esportes',
    quantities: {
      analogico: 15,
      semFio: 10,
      extensao: 25,
      dBasico: 4,
      dEspecial: 1,
      ipBasico: 20,
      fCabeca: 1,
      sMesa: 0,
      software: 30,
      virtual: 8,
    },
    status: 'Encerrado',
    dataAssinatura: '25/04/2025',
    observacoes: 'Contrato finalizado por escoamento de prazo.',
  },
  {
    id: 'C-12',
    contrato: 'Contrato 190/2025',
    secretaria: 'SETUR - Secretaria de Turismo',
    quantities: {
      analogico: 18,
      semFio: 14,
      extensao: 30,
      dBasico: 6,
      dEspecial: 3,
      ipBasico: 30,
      fCabeca: 2,
      sMesa: 0,
      software: 45,
      virtual: 12,
    },
    status: 'Ativo',
    dataAssinatura: '01/05/2025',
    observacoes: 'Infraestrutura dos centros estaduais de informação turística.',
  },
];

export function getContractPvfTotal(contract: Contract): number {
  return Object.values(contract.quantities).reduce((acc, curr) => acc + curr, 0);
}

export function getContractValue(contract: Contract, prices: PvfPrices): number {
  return Object.entries(contract.quantities).reduce((acc, [key, qty]) => {
    const price = prices[key as PvfKey] || 0;
    return acc + qty * price;
  }, 0);
}

export function formatCurrency(value: number): string {
  return new Intl.NumberFormat('pt-BR', {
    style: 'currency',
    currency: 'BRL',
  }).format(value);
}
